### ISSUE TITLE
Missing file error

### ISSUE THREAD

**Issue by polsvoice** [Real-Change/emerald-city-resource-guide#162]
I'm getting this error when I run `sudo docker-compose up`

```
Error: Cannot find module 'csv/dist/cjs/sync.cjs'
```

**Comment by MasonM** [comment]
That indicates you're missing an NPM dependency. Try running `docker-compose run --rm node npm install` first.

I've been thinking about adding a `Makefile` to simplify things (e.g. you could run `make install` to install dependencies). Does that sound good to you?

**Comment by polsvoice** [comment]
Thanks! That worked!

I don't have any problem running `make install`. Do you think that there could be a better way to do this using a Dockerfile, though? I'm a novice with Docker, but I thought the whole point was that you didn't have to update dependencies or run any extra commands.

**Comment by MasonM** [comment]
@polsvoice Okay, I went ahead and added a `Makfile` in https://github.com/Real-Change/emerald-city-resource-guide/pull/163

Docker handles building containers and running them, but it can't "know" when an NPM dependency is out-of-date, because it operates at a lower level than NPM. NPM uses the `package.json` and `package-lock.json` files to track dependencies and determine what's up-to-date, but from Docker's perspective, they're just regular files.
